#!/bin/bash
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
python test.py &
